# Copyright 2026 Anthropic PBC
# SPDX-License-Identifier: Apache-2.0

"""V_τ → B_rec with B_rec*·B_rec = Q, by the τ-tower descent of paper §6.2 and
Appendix D (the implementation's replacement for step 3's Z^n-LIP solve; the
paper makes no provable claim for the tower's runtime, only for its steps).

Each level extracts a free O_{L'}-basis of M_{V_τ} = B⁻¹·O_{L'}² by paper
Lemma D.4: (i) M is generated by the columns of (I+V_τ)/2 and (I−V_τ)/(2ζ);
(ii) the alternating O_{L'}-form μ = ½Tr_{L/L'}∘det is unimodular on M, so any
(x,y) with μ(x,y) = 1 is a free basis. We solve μ(x,y) = 1 by a Bézout step
(pari `idealaddtoone`).
"""

from __future__ import annotations

import time

from hawk_recover import ring
from hawk_recover.cocycle import cocycle_lattice_small
from hawk_recover.params import HawkParams
from hawk_recover.svp import solve_svp_gram
from hawk_recover.types import Intertwiner, PublicKey, RecoveredBasis, require


def _log(verbose: bool, t0: float, msg: str) -> None:
    if verbose:
        print(f"[tower {time.time() - t0:7.1f}s] {msg}", flush=True)


def _mat_to_Qlist(G, n: int):
    """2×2 Sage matrix over L with integral entries → coefficient-list tuple."""
    from sage.all import ZZ

    out = []
    for r in range(2):
        for c in range(2):
            co = list(G[r, c])
            out.append([int(ZZ(co[k])) if k < len(co) else 0 for k in range(n)])
    return tuple(out)


def _amb_to_matrix(amb, L, z, n: int):
    """Ambient 4n coordinate vector → 2×2 matrix over L (generic implementation)."""
    from sage.all import ZZ

    return ring.gmat(
        L,
        [
            [
                sum(ZZ(int(amb[(2 * r + c) * n + k])) * z**k for k in range(n))
                for c in range(2)
            ]
            for r in range(2)
        ],
    )


def _is_aside(amb, n: int) -> bool:
    """W ≡ I (mod 2) in ambient coordinates."""
    for r in range(2):
        for c in range(2):
            for k in range(n):
                expect = 1 if (r == c and k == 0) else 0
                if (int(amb[(2 * r + c) * n + k]) - expect) % 2 != 0:
                    return False
    return True


def _module_basis(
    Vtau, G, L, zeta, c, tau, dL: int, *, verbose: bool = False, t0: float = 0.0
):
    """Free O_{L'}-basis M_p (det 1) of the V_τ-projector module M, such that
    M_p*·G·M_p is τ-fixed and integral; symplectic extraction via the μ-form,
    which is unimodular on M (paper Lemma D.4).
    Raises RuntimeError when no primitive x is found (degenerate candidate, or
    a b-summand cocycle W(0,·) rather than the a-side ±V_τ)."""
    from sage.all import QQ, ZZ, CyclotomicField, pari, vector

    dK = dL // 2
    I2 = ring.gidentity(L, 2)
    Vtau = ring.to_generic(Vtau)
    P1 = (I2 + Vtau) / 2
    P2 = (I2 - Vtau) / (2 * zeta)
    gens_L = [P1.column(0), P1.column(1), P2.column(0), P2.column(1)]

    # L' = fixed field of τ, identified with Q(ζ_{dL}) via ζ' ↦ ζ².
    Ls = CyclotomicField(dL, f"zs{dL}")
    zs = Ls.gen()
    emb = Ls.hom([zeta**2], L)

    def split(x):
        """x ∈ L → (even, odd) ∈ L'² with x = emb(even) + ζ·emb(odd)."""
        co = list(x) + [0] * (dL - len(list(x)))
        return (
            Ls(sum(QQ(co[2 * j]) * zs**j for j in range(dK))),
            Ls(sum(QQ(co[2 * j + 1]) * zs**j for j in range(dK))),
        )

    gens4 = [vector(Ls, list(split(g[0])) + list(split(g[1]))) for g in gens_L]
    nf = pari(Ls)

    def mu(a, b):
        """Alternating O_{L'}-bilinear form, unimodular on M."""
        return (a[0] * b[2] - a[2] * b[0]) + zs * (a[1] * b[3] - a[3] * b[1])

    candidates = list(gens4)
    candidates += [gens4[i] + gens4[j] for i in range(4) for j in range(i + 1, 4)]

    from cypari2.handle_error import PariError

    f1 = f2 = None
    for x in candidates:
        m = [mu(x, g) for g in gens4]
        nonzero = [(j, mj) for j, mj in enumerate(m) if mj != 0]
        if not nonzero:
            continue  # x pairs to zero with everything — in the radical
        try:
            # Bézout: 1 = Σ e_j with e_j ∈ (m_j). idealaddtoone raises PariError
            # exactly when the ideals don't sum to O_{L'}, i.e. x is not primitive
            # (μ(M,M) ⊊ O_{L'} for b-summand candidates — Lemma D.4's failure case).
            parts = nf.idealaddtoone([nf.idealhnf(pari(mj)) for _, mj in nonzero])
        except PariError as e:
            _log(verbose, t0, f"candidate not μ-primitive ({e}); trying next")
            continue
        # e_j = c_j·m_j  ⇒  c_j = e_j/m_j (exact in L'); y = Σ c_j·g_j.
        y = vector(Ls, [0, 0, 0, 0])
        for (j, mj), ej_pari in zip(nonzero, parts, strict=True):
            # idealaddtoone returns nf elements in basis form (t_COL) when the
            # ideal is given by an HNF matrix, else algebraic (t_POLMOD).
            ej_alg = nf.nfbasistoalg(ej_pari) if ej_pari.type() == "t_COL" else ej_pari
            y = y + (Ls(ej_alg) / mj) * gens4[j]
        require(mu(x, y) == 1, "Bézout reconstruction failed")
        f1, f2 = x, y
        break
    if f1 is None:
        raise RuntimeError(
        "no primitive element found — candidate is a b-summand cocycle or degenerate"
    )

    for f, nm in ((f1, "f1"), (f2, "f2")):
        require(
            all(co in ZZ for i in range(4) for co in list(f[i])), f"{nm} not integral"
        )

    # Gauss reduction under the G-Hermitian form, rounding quotients to O_{L'}
    # (keeps coefficient growth polynomial; empirically always ≤ 80 iterations).
    def to_L2(v4):
        return vector(
            L, [emb(v4[0]) + zeta * emb(v4[1]), emb(v4[2]) + zeta * emb(v4[3])]
        )

    def hermG(a, b):
        al, bl = to_L2(a), to_L2(b)
        return sum(c(al[i]) * sum(G[i, j] * bl[j] for j in range(2)) for i in range(2))

    def rnd_Ls(q):
        co = list(q) + [0] * (dL - len(list(q)))
        return Ls(sum(ZZ(round(QQ(co[2 * j]))) * zs**j for j in range(dK)))

    for _ in range(80):
        h11, h22 = hermG(f1, f1), hermG(f2, f2)
        if abs(QQ(h22.norm())) < abs(QQ(h11.norm())):
            f1, f2 = f2, f1
            continue
        q = rnd_Ls(hermG(f1, f2) / h11)
        if q == 0:
            break
        f2 = f2 - q * f1

    Mp = ring.gmat(L, [list(to_L2(f1)), list(to_L2(f2))]).transpose()
    # det(Mp) lies in emb(L') because det(V_τ)=1 forces τ(det)=det; dividing a
    # column by it is an L'-scalar operation and keeps M_p's columns in the
    # τ-twisted eigenspace (which is what makes G' τ-fixed).
    d = Mp.det()
    Mp = Mp * ring.gmat(L, [[1, 0], [0, d**-1]])
    require(Mp.det() == 1, "det ≠ 1 after normalization")
    return Mp


def _base_case(Gps, Ls, zs, cs, dLs: int):
    """Solve the LIP instance Gps over L_small by enumeration: find an
    orthonormal pair under the Hermitian form; its inverse matrix N is the
    recovered basis at this level (N*·N = Gps)."""
    from sage.all import ZZ, QuadraticForm, matrix, vector

    def herm(x, y):
        return sum(cs(x[i]) * sum(Gps[i, j] * y[j] for j in range(2)) for i in range(2))

    basis = [
        vector(Ls, [zs**k if comp == 0 else 0, zs**k if comp == 1 else 0])
        for comp in range(2)
        for k in range(dLs)
    ]
    Gd = matrix(
        ZZ,
        2 * dLs,
        2 * dLs,
        [
            [ZZ(herm(basis[i], basis[j]).trace()) for j in range(2 * dLs)]
            for i in range(2 * dLs)
        ],
    )
    QF = QuadraticForm(ZZ, 2 * Gd)
    sv = QF.short_vector_list_up_to_length(dLs + 1)
    svs = [vector(ZZ, v) for v in sv[dLs]] if dLs < len(sv) else []
    cands = [sum(ZZ(v[i]) * basis[i] for i in range(2 * dLs)) for v in svs]
    I2 = ring.gidentity(Ls, 2)
    for i1 in range(len(cands)):
        for i2 in range(i1 + 1, len(cands)):
            if herm(cands[i1], cands[i2]) != 0:
                continue
            M_ = ring.gmat(
                Ls, [[cands[i1][0], cands[i2][0]], [cands[i1][1], cands[i2][1]]]
            )
            if ring.star(M_, cs) * Gps * M_ == I2:
                return M_.inverse()
    raise AssertionError(f"base case (dim {2 * dLs}): no orthonormal pair found")


def _recurse(ell: int, G, preset_V, maxb: dict[int, int], *, verbose: bool, t0: float):
    from sage.all import QQ, ZZ

    L, z, c, tauH, _ = ring.field_and_homs(ell)
    dL, dK = 1 << (ell - 1), 1 << (ell - 2)
    G = ring.to_generic(G)
    beta_trace: dict[int, int | str] = {}

    # candidate a-side cocycles at this level
    if preset_V is not None:
        cands = [(True, ring.to_generic(preset_V))]
        beta_trace[ell] = "PRESET"
    else:
        p_sub = HawkParams.for_ell(ell)
        lat = cocycle_lattice_small(_mat_to_Qlist(G, dL), p_sub, verbose=verbose)
        shorts, beta_hit = solve_svp_gram(
            lat.Gram_tau,
            p_sub.lam1sq,
            schedule=range(4, maxb.get(ell, 60) + 1, 3),
            verbose=verbose,
            tag=f"ℓ={ell}",
            return_beta=True,
        )
        # β=0 means no BKZ was needed (plain LLL or exact enumeration).
        # Expected count of minimal vectors is n/2+1 up to sign (Lemma 4.4(ii)).
        beta_trace[ell] = beta_hit
        I2 = ring.gidentity(L, 2)
        cands = []
        for w in shorts:
            amb = w * lat.LB
            Vp = _amb_to_matrix(amb, L, z, dL)
            if Vp * ring.mat_apply(Vp, tauH) != I2:
                continue
            cands.append((_is_aside(amb, dL), Vp))
        cands.sort(key=lambda x: not x[0])  # a-side candidates first
    require(bool(cands), f"no cocycle candidates at ℓ={ell}")

    # try candidates until the descent works
    for idx, (_, Vc) in enumerate(cands):
        try:
            Mp = _module_basis(
                Vc, G, L, z, c, tauH, dL, verbose=verbose and idx == 0, t0=t0
            )
        except (RuntimeError, AssertionError):
            continue
        Gp = ring.star(Mp, c) * G * Mp
        if ring.mat_apply(Gp, tauH) != Gp:
            continue
        if not all(co in ZZ for e in Gp.list() for co in list(e)):
            continue

        # Restrict G' to L' (even coefficients only).
        Ls, zs, cs, _, _ = ring.field_and_homs(ell - 1)

        def restrict(x):
            co = list(x) + [0] * (dL - len(list(x)))
            return Ls(sum(QQ(co[2 * j]) * zs**j for j in range(dK)))  # noqa: B023

        Gps = ring.gmat(Ls, [[restrict(Gp[i, j]) for j in range(2)] for i in range(2)])

        if ell - 1 <= 3:
            Ns = _base_case(Gps, Ls, zs, cs, dK)
            sub_trace: dict[int, int | str] = {ell - 1: "BASE"}
            _log(verbose, t0, f"[ℓ={ell - 1}] base case solved ✓")
        else:
            Ns, sub_trace = _recurse(ell - 1, Gps, None, maxb, verbose=verbose, t0=t0)
        beta_trace.update(sub_trace)

        embed = Ls.hom([z**2], L)
        N = ring.gmat(L, [[embed(Ns[i, j]) for j in range(2)] for i in range(2)])
        return N * Mp.inverse(), beta_trace

    raise AssertionError(f"no candidate gave a valid descent at ℓ={ell}")


def recover_basis(
    itw: Intertwiner, pk: PublicKey, *, verbose: bool = False
) -> RecoveredBasis:
    """Intertwiner + PublicKey → B_rec with B_rec*·B_rec = Q."""
    from sage.all import ZZ

    p = pk.params
    t0 = time.time()
    L, z, c, _, _ = ring.field_and_homs(p.ell)
    G = pk.Q(L)

    B_rec, beta_trace = _recurse(
        p.ell, G, itw.V, p.tower_max_beta, verbose=verbose, t0=t0
    )
    _log(verbose, t0, f"descent complete, β-trace: {beta_trace}")

    eq_G = bool(ring.star(B_rec, c) * B_rec == G)
    in_OL = all(co in ZZ for e in B_rec.list() for co in list(e))
    d = B_rec.det()
    det_unit = bool(abs(ZZ((d * c(d)).norm())) == 1)

    n = p.n
    B_list = tuple(
        [int(ZZ(co)) for co in (list(B_rec[r, cc]) + [0] * n)[:n]]
        for r in range(2)
        for cc in range(2)
    )
    rb = RecoveredBasis(
        params=p,
        B_rec_list=B_list,
        beta_trace=beta_trace,
        eq_G=eq_G,
        in_OL=in_OL,
        det_unit=det_unit,
    )
    rb.check()
    return rb
